// <auto-generated />
namespace ProjetoFinalAliare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class BD_Inicio1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BD_Inicio1));
        
        string IMigrationMetadata.Id
        {
            get { return "202205252213002_BD_Inicio1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
