// <auto-generated />
namespace ProjetoFinalAliare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class BD_Inicio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BD_Inicio));
        
        string IMigrationMetadata.Id
        {
            get { return "202205201828409_BD_Inicio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
