// <auto-generated />
namespace ProjetoFinalAliare.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Curso : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Curso));
        
        string IMigrationMetadata.Id
        {
            get { return "202205282221081_Curso"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
